### ISSUE TITLE
Country Request Bugged (?)

### ISSUE THREAD

**Issue by cedricpollefeys** [TakeawayAPI/php-takeaway#4]
This API _seems to_ only work for Dutch food. I was stuck for hours without responses from every country code except the Netherlands when trying to find restaurants. I decided to run 'getCountryByCode' in a loop (0->99) and then dumped all the info inside into an echo to see; the result was that only the second entry (aka index 1/The Netherlands) gave anything back. Is there anything that can be done about this? Is anything wrong from my side or is this API not supported outside of The Netherlands anymore.

**Comment by DanielleHuisman** [comment]
For other countries the URL and language code need to be changed. They are currently defined [here](https://github.com/TakeawayAPI/php-takeaway/blob/master/src/Takeaway.php#L12).

An [example of other values](https://github.com/TakeawayAPI/node-takeaway/blob/master/example/countries.js#L18) can be found in the Node.js version of this library.

**Comment by DanielleHuisman** [comment]
This has been fixed in #6, see #7 for examples.
